apiVersion: v1
kind: Service
metadata:
  name: rit-mysql
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    app: rit-mysql
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rit-mysql
spec:
  serviceName: rit-mysql
  replicas: 2
  selector:
    matchLabels:
      app: rit-mysql
  template:
    metadata:
      labels:
        app: rit-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rit-mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql123"
          volumeMounts:
            - name: rit-pv
              mountPath: /var/lib/mysql
        - name: flask-app
          image: mysql:8
          env:
            - name: MYSQL_HOST
              value: "localhost"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mysql123"
            - name: MYSQL_DATABASE
              value: "yourdbname"
          ports:
            - containerPort: 5000
  volumeClaimTemplates:
    - metadata:
        name: rit-pv
      spec:
        storageClassName: rit-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

